- name: Fetch package
  get_url: url=http://s3.amazonaws.com/influxdb/influxdb_{{ influxdb.version }}_amd64.deb dest=/usr/local/src/influxdb_{{ influxdb.version }}_amd64.deb

- name: Install package
  command: dpkg --skip-same-version -i /usr/local/src/influxdb_{{ influxdb.version }}_amd64.deb
  register: dpkg_result
  changed_when: "dpkg_result.stdout.startswith('Selecting')"

- name: Update config
  template: src=influxdb.conf dest=/etc/influxdb/influxdb.conf

- name: Start InfluxDB
  service: name=influxdb state=restarted
  notify:
    - wait for influxdb port